version: "3.8"

services:
  web_app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=api
      - FLASK_ENV=development
    command: flask run

  db:
    container_name: "db"
    restart: always
    image: postgres:alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

volumes:
  pgdata: