
version: "3.8"

services:
  db:
    container_name: "db"
    restart: always
    image: postgres:alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - "pgdata:/var/lib/postgresql/data_inventory"

volumes:
  pgdata: